baseURL = 'https://ericekholm.com/'
languageCode = 'en-us'
title = 'Eric Ekholm'
copyright = "© Eric Ekholm"
theme = 'archie'

[params]
  mode = "auto"
  useFullHTMLContent = false

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/ekholme"

[[params.social]]
name = "X"
icon = "x"
url = "https://x.com/ekholm_e"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 4

[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 5

[[menu.main]]
name = "AI"
url = "/ai"
weight = 6
